# Generated by Django 4.1.7 on 2023-02-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="assets/images")),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=250)),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
